# Generated by Django 3.2.12 on 2023-02-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20230226_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_parent': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.area'),
        ),
    ]
