# Generated by Django 3.2.12 on 2023-02-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_area_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_parent': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.area'),
        ),
    ]
