# Generated by Django 3.2.12 on 2023-03-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_street_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='area',
        ),
    ]
