# Generated by Django 4.1.7 on 2023-04-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20230313_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='osm_imported',
            field=models.BooleanField(default=False),
        ),
    ]
