# Generated by Django 4.1.7 on 2023-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_appointment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
