# Generated by Django 4.1.7 on 2023-10-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_appointment_is_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='appointment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='appointment_max',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
