# Generated by Django 4.1.7 on 2024-02-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='appointment_count',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_full',
        ),
    ]
