# Generated by Django 4.1.7 on 2024-02-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_timeslot_appointment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='area',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.area'),
        ),
    ]
